require('dotenv').config()
const bodyParser = require('body-parser')
const compression = require('compression')
const cors = require('cors')
const express = require('express')
const helmet = require('helmet')
const morgan = require('morgan')
const path = require('path')
const port = process.env.PORT
const routerNavigation = require('./routes')

const app = express()
app.use(bodyParser.json())
app.use(express.urlencoded({ extended: true }))
app.use(compression())
app.use(cors())
app.options('*', cors())
app.use(helmet())
app.use(morgan('dev'))
app.use('/backend1/api/v1', routerNavigation)
app.use('/backend1/api', express.static(path.join(__dirname, 'uploads')))

app.listen(port, () => {
  console.log(`App is listening on port ${port}`)
})
